name: mindclash
description: A local pass-and-play mobile trivia game.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.10.0
  riverpod_annotation: ^4.0.2

dev_dependencies:
  build_runner: ^2.11.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.5
  json_serializable: ^6.12.0
  mocktail: ^1.0.4
  riverpod_generator: ^4.0.3
  very_good_analysis: ^10.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
